kind = "web"
previewPath = "/"
title = "Hospital Website"
version = "1.0.0"
id = "artifacts/hospital-website"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18213

[services.development]
run = "pnpm --filter @workspace/hospital-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/hospital-website", "run", "build" ]
publicDir = "artifacts/hospital-website/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18213"
BASE_PATH = "/"
